name: swipe_cards
description: Tinder like swipe cards.
version: 1.0.0
homepage: https://github.com/AnupKumarPanwar/swipe_cards
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter



flutter: null
